trigger:
- main

pool:
  name: Default  # Matches your self-hosted agent pool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\\Program Files\\Microsoft\\jdk-17.0.14.7-hotspot'  # Absolute path to JDK on your agent machine
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
